Repository ontoportal-lirmm/ontologies_api, pull requests merged in 2024-07, with the labels that each got.

#85 Fix: remove duplicated agents root
  controllers/agents_controller.rb
Labels: bug

#84 Feature: implement ontology agents endpoint
  Gemfile.lock
  controllers/agents_controller.rb
  test/controllers/test_ontologies_controller.rb
Labels: enhancement

#82 Fix: Search multilingual values filter
  controllers/search_controller.rb
  helpers/search_helper.rb
  test/controllers/test_annotator_controller.rb
  test/controllers/test_search_controller.rb
Labels: bug, enhancement
